-- MySQL Script generated by MySQL Workbench
-- Fri May 26 10:01:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`results` (
  `pubMed ID` INT NOT NULL,
  `url` VARCHAR(50) NOT NULL,
  `Title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`pubMed ID`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `pubMed ID_UNIQUE` (`pubMed ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Toepassing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Toepassing` (
  `Toepassing` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Toepassing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lox` (
  `lox` VARCHAR(45) NOT NULL,
  `NCBI Prot_ID` VARCHAR(45) NULL,
  `fullname` VARCHAR(45) NULL,
  PRIMARY KEY (`lox`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organism` (
  `Name` VARCHAR(45) NOT NULL,
  `Kingdom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keywords` (
  `keyword_ID` INT NOT NULL,
  `keyword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`keyword_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`results_has_Organism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`results_has_Organism` (
  `results_pubMed ID` INT NOT NULL,
  `Organism_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`results_pubMed ID`, `Organism_Name`),
  INDEX `fk_results_has_Organism_Organism1_idx` (`Organism_Name` ASC),
  INDEX `fk_results_has_Organism_results1_idx` (`results_pubMed ID` ASC),
  CONSTRAINT `fk_results_has_Organism_results1`
    FOREIGN KEY (`results_pubMed ID`)
    REFERENCES `mydb`.`results` (`pubMed ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_has_Organism_Organism1`
    FOREIGN KEY (`Organism_Name`)
    REFERENCES `mydb`.`Organism` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`results_has_Lox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`results_has_Lox` (
  `results_pubMed ID` INT NOT NULL,
  `Lox_lox` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`results_pubMed ID`, `Lox_lox`),
  INDEX `fk_results_has_Lox_Lox1_idx` (`Lox_lox` ASC),
  INDEX `fk_results_has_Lox_results1_idx` (`results_pubMed ID` ASC),
  CONSTRAINT `fk_results_has_Lox_results1`
    FOREIGN KEY (`results_pubMed ID`)
    REFERENCES `mydb`.`results` (`pubMed ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_has_Lox_Lox1`
    FOREIGN KEY (`Lox_lox`)
    REFERENCES `mydb`.`Lox` (`lox`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`results_has_Toepassing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`results_has_Toepassing` (
  `results_pubMed ID` INT NOT NULL,
  `Toepassing_Toepassing` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`results_pubMed ID`, `Toepassing_Toepassing`),
  INDEX `fk_results_has_Toepassing_Toepassing1_idx` (`Toepassing_Toepassing` ASC),
  INDEX `fk_results_has_Toepassing_results1_idx` (`results_pubMed ID` ASC),
  CONSTRAINT `fk_results_has_Toepassing_results1`
    FOREIGN KEY (`results_pubMed ID`)
    REFERENCES `mydb`.`results` (`pubMed ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_has_Toepassing_Toepassing1`
    FOREIGN KEY (`Toepassing_Toepassing`)
    REFERENCES `mydb`.`Toepassing` (`Toepassing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `idAuthor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`results_has_Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`results_has_Author` (
  `results_pubMed ID` INT NOT NULL,
  `Author_idAuthor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`results_pubMed ID`, `Author_idAuthor`),
  INDEX `fk_results_has_Author_Author1_idx` (`Author_idAuthor` ASC),
  INDEX `fk_results_has_Author_results1_idx` (`results_pubMed ID` ASC),
  CONSTRAINT `fk_results_has_Author_results1`
    FOREIGN KEY (`results_pubMed ID`)
    REFERENCES `mydb`.`results` (`pubMed ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_has_Author_Author1`
    FOREIGN KEY (`Author_idAuthor`)
    REFERENCES `mydb`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publication_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publication_date` (
  `date` DATE NOT NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`results_has_publication_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`results_has_publication_date` (
  `results_pubMed ID` INT NOT NULL,
  `publication_date_date` DATE NOT NULL,
  PRIMARY KEY (`results_pubMed ID`, `publication_date_date`),
  INDEX `fk_results_has_publication_date_publication_date1_idx` (`publication_date_date` ASC),
  INDEX `fk_results_has_publication_date_results1_idx` (`results_pubMed ID` ASC),
  CONSTRAINT `fk_results_has_publication_date_results1`
    FOREIGN KEY (`results_pubMed ID`)
    REFERENCES `mydb`.`results` (`pubMed ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_has_publication_date_publication_date1`
    FOREIGN KEY (`publication_date_date`)
    REFERENCES `mydb`.`publication_date` (`date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`results_has_keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`results_has_keywords` (
  `results_pubMed ID` INT NOT NULL,
  `keywords_keyword_ID` INT NOT NULL,
  PRIMARY KEY (`results_pubMed ID`, `keywords_keyword_ID`),
  INDEX `fk_results_has_keywords_keywords1_idx` (`keywords_keyword_ID` ASC),
  INDEX `fk_results_has_keywords_results1_idx` (`results_pubMed ID` ASC),
  CONSTRAINT `fk_results_has_keywords_results1`
    FOREIGN KEY (`results_pubMed ID`)
    REFERENCES `mydb`.`results` (`pubMed ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_has_keywords_keywords1`
    FOREIGN KEY (`keywords_keyword_ID`)
    REFERENCES `mydb`.`keywords` (`keyword_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Searchterms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Searchterms` (
  `term` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`term`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
